// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AskChatGPT
{
    internal sealed partial class Vsix
    {
        public const string Id = "AskChatGPT.809330fd-3f8f-4d94-98a8-7214d273c896";
        public const string Name = "AskChatGPT";
        public const string Description = @"This extension allows you to get help from ChatGPT directly inside Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Adolfo Marinucci";
        public const string Tags = "";
    }
}
